FROM mcr.microsoft.com/devcontainers/python:3

WORKDIR /workspace

RUN apt-get update && apt-get install -y \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

COPY ./backend/requirements.txt ./backend/requirements.txt
RUN pip install --no-cache-dir -r ./backend/requirements.txt \
    && apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*
